# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ACT EverQuest DPS Plugin

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Download ACT dependency
        run: Invoke-WebRequest https://advancedcombattracker.com/download.php?id=57 -OutFile ACTv3.zip
      - name: Extract ACT files
        run: 7z x ACTv3.zip
      - name: Restore packages
        run: msbuild -p:RestorePackagesConfig=true -t:restore
      - name: Build solution
        run: msbuild ACT_EverQuest_DPS_Plugin.sln -t:build -property:Configuration=Release
