# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ACT EverQuest DPS Plugin

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Download ACTv3 file
        run: Invoke-WebRequest https://advancedcombattracker.com/download.php?id=56 -OutFile ACTv3-Setup.exe
      - name: List Downloaded to Folder
        run: dir ${{ github.workspace }}
      - name: Extract ACT files
        run: ${{ github.workspace }}\ACTv3-Setup.exe /S
      - name: Build solution
        run: msbuild -t:build -property:Configuration=Release EverQuestDPSPlugin/EverQuestDPSPlugin.csproj 
